### PR TITLE
Database for the extracted files from the resume

### PR DESCRIPTION
**Pull request by Christian-Kofi-Okyere**
### Changes Introduced
- Added functionality to handle resume uploads in the `/application` route.
- Integrated `extract_text_from_pdf` to extract fields from uploaded resumes.
- Mapped extracted data to the `ApplicantResume` model, including:
  - `name`
  - `education`
  - `experience`
  - `skills`
  - `certifications`
  - `summary`
- Established a relationship between `ApplicantResume` and `ApplicantInformation` using `student_id`.

### How to Test
1. Upload a sample PDF resume via the application form.
2. Verify that:
   - A new record is created in the `applicant_resume` table.
   - Extracted fields (e.g., name, education, skills) match the content of the uploaded resume.
   - The `applicant_resume` record is linked to the correct `applicant_information` record using `student_id`.

### Why This Change
- Streamlines the management of resume data by automating extraction and storage.
- Reduces manual effort in populating applicant details during the application process.
- Ensures consistency and accuracy in storing applicant data.

### Potential Impact
- Requires the `resume` field in the application form to be mandatory for processing.
- Only supports `.pdf` files; invalid file types or improperly formatted resumes may result in partial or missing data extraction.

### CODE REVIEW

**Review by akiola — DISMISSED** [review]

**Review by agpalm25 — CHANGES_REQUESTED** [review]
Submission doesn't work if the file isn't of the accepted formatting, maybe make it so if the file isn't accepted, you just don't initialize it.

Alongside this, some data from the resume overwrites answers gained from the application, should we not have resume data viewable on another page instead?

**Comment by James23xr** [comment]
I noticed the information from the resume overrides some of the information an applicant provides during their application

**Comment by Christian-Kofi-Okyere** [comment]
The override is because I want the resume submitted and the one filing it to have the same details. If you fill the form and provide a resume consistent to what you fill, it should work just fine without the override

**Comment by Christian-Kofi-Okyere** [comment]
> The override is because I want the resume submitted and the one filing it to have the same details. If you fill the form and provide a resume consistent to what you fill, it should work just fine without the override

@agpalm25 
@James23xr

**Comment by Christian-Kofi-Okyere** [comment]
The file needs to be a pdf format in order for the extraction to work fine. It's a requirement for the pymupdf I am using. Also, the resume is a required component because we the the information on there for the admins to access and make decisions 
@agpalm25

**Comment by agpalm25** [comment]
> The file needs to be a pdf format in order for the extraction to work fine. It's a requirement for the pymupdf I am using. Also, the resume is a required component because we the the information on there for the admins to access and make decisions @agpalm25

in the original application and in the meetings, it hasn't been made to be required, and I tested submitting an application with a pdf that doesn't match the formatting expected, and it simply refreshed the page without submitting the application. I think it would be fine to push this, but is it okay if i add some changes or would you prefer it to stay like this?

**Pull request closed without merging**
